### ISSUE TITLE
structure padding

### ISSUE THREAD

**Issue by felixangell** [felixangell/krug#89]
structures need to be padded/aligned

**Comment by Jackojc** [comment]
good idea

**Comment by s0cks** [comment]
Definitely & May I also suggest packing the structure as much as possible to preserve memory overhead for objects?

**Comment by felixangell** [comment]
@s0cks indeed, this will be specified with a compiler macro:

```
#[repr(packed)]
type Foo struct {

}
```

or equivalent, I'm yet to make an issue for this though

**Comment by s0cks** [comment]
Maybe it should be done automatically? I mean macros are cool though! Maybe have compiler flag to pack structs for embedded systems?

**Comment by felixangell** [comment]
@s0cks I'm not sure if I'd want to do that, I kinda want the language/compiler to be as simple as possible to the point where everything that happens is somewhat transparent. 

A compiler flag though for this would be possible but I think usually when you do this it's because you want it in specific cases. I'm no embedded programmer but I still think padding structures, etc. is done for speed of computation though? 

Theres only certain scenarios where you want to pack a structure, and they are usually per-structure so I feel like a macro is pretty much the tool for the job here.

But like I said, I'm no embedded programmer and I might be painfully incorrect about this, though the languages primary target isn't really for embedded systems though this would be a cool thing to have the language working on

**Comment by felixangell** [comment]
@s0cks thanks for the writeup on this. been super busy lately so i havent had time to work on krug but when i do thisll probably be the first thing i tackle :)
